### ISSUE TITLE
Get inspector mode operating again

### ISSUE THREAD

**Issue by mmbayles** [Grasslands-2/GrazeScape#108]

**Comment by emchasen** [comment]
inspector mode should be able to visualize any of the raster layers

**Comment by zhassler** [comment]
Still working on this issue.  It works when using direct mapping to the rasters urls, but that wont work when we use the code in the containers.  I have to go around the WEI firewall with the proxy.  But we need can not hit the url directly through the proxy.  I have to download a extent of the rasters to display it.  Currently the problem is the standby layer can not change the source on the fly.  I am working on either only permanently setting the source to the raster extent location, or recreating the layer each time the layer is turned on or off in the layer menu.
